Repository ilkeraslan/dota2compose, pull requests merged in 2022-10, with the labels that each got.

#26 #25 Exclude idea files
  .gitignore
  README.md
Labels: infra

#31 #30 Upgrade target sdk to 33
  app/build.gradle.kts
Labels: hacktoberfest-accepted, infra

#33 #32 Bump compose compiler to 1_3_2
  app/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: hacktoberfest-accepted, infra

#34 #29 Bump coil to 2_2_2
  README.md
  app/build.gradle.kts
  app/src/main/java/me/ilker/dota2compose/MainActivity.kt
  app/src/main/java/me/ilker/dota2compose/ui/screens/HeroesScreen.kt
  app/src/main/java/me/ilker/dota2compose/ui/screens/TeamsScreen.kt
  app/src/main/java/me/ilker/dota2compose/ui/teams/Teams.kt
Labels: infra

#36 feat: added splash screen
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/me/ilker/dota2compose/MainActivity.kt
  app/src/main/java/me/ilker/dota2compose/ui/teams/Teams.kt
  app/src/main/res/drawable/logo.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, hacktoberfest-accepted
